# What is the total revenue generated by male vs. female customers?
Select gender, Sum(purchase_amount) as revenue
from mytable
group by gender

# Which customers used a discount but still spent more 
-- than the average purchase amount? 
Select customer_id, purchase_amount
from mytable
where discount_applied = "Yes" and purchase_amount > 
(select avg(purchase_amount) from mytable)

# Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
from mytable 
Group By item_purchased
order by avg(review_rating) DESC
Limit 5

# Compare the average Purchase Amounts between Standard and Express Shipping. 
Select Shipping_type,
	Round(AVG(purchase_amount),2) as "Average Purchase Amount"
from mytable
where shipping_type IN ("Standard", "Express")
Group by shipping_type

# Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
Select subscription_status,
	Count(customer_id) as total_customers,
	round(avg(purchase_amount),1) as avg_spend,
    round(sum(purchase_amount),1)as total_revenue
From mytable
Group by subscription_status
Order by total_revenue, avg_spend DESC

# Which 5 products have the highest percentage of purchases with discounts applied?
Select item_purchased,
	round(sum(
    Case 
		When discount_applied = "Yes" Then 1 
		Else 0
    END)/Count(*)*100,2) as discount_rate
    from mytable
    group by item_purchased
    order by discount_rate DESC
    Limit 5
    
# Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WIth customer_type as 
(Select 
case
	When previous_purchases= 1 Then "New"
    When previous_purchases Between 2 and 10 Then "Returning"
    ELse "Loyal"
END as customer_segmentation 
from mytable)
Select customer_segmentation, count(*) as no_of_customers
from customer_type
group by customer_segmentation

#   Are customers who are repeat buyers (more than 5 previous purchases) 
-- also likely to subscribe?
Select subscription_status,
	count(customer_id) as repeated_customers
From mytable 
where previous_purchases > 5
group by subscription_status

# What is the revenue contribution of each age group? 
Select age_group,
	sum(purchase_amount) as revenue
from mytable
group by age_group
order by revenue DESC

